server:
  port: 1111
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: -1
  servlet:
    context-path: /RedisLock

spring:
  redis:
    host: 192.168.50.236
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password:
    #连接超时时间（毫秒）
    timeout: 30000
    jedis:
      pool:
        #连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait:
        #连接池中的最大空闲连接
        max-idle: 8
        #连接池中的最小空闲连接
        min-idle: 0
